name = "donde-esta-tu-local"
account_id = "173bf7921f79923475ce95a48b845583"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "donde-esta-tu-local"
database_id = "4a8ca183-7bf2-4def-b5a8-7bc353a8581e"

[env.staging]
name = "donde-esta-tu-local-staging"
account_id = "173bf7921f79923475ce95a48b845583"
workers_dev = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "donde-esta-tu-local-staging"
database_id = "3f44a2a9-c325-4b76-935e-2e955dbe5490"
