name = "donde-esta-tu-local"
account_id = "173bf7921f79923475ce95a48b845583"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "donde-esta-tu-local"
database_id = "787be1af-7e5d-4d0b-b132-89754e638924"