name: Deploy

on:
  push:
    branches:
      - main

env:
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_REDIRECT_URI: https://donde-esta-tu-local.callepuzzle-rkjp.workers.dev/login/callback
  DATABASE_URL: file:./dev.db

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        uses: CallePuzzle/envvar-to-dotenv-action@v1.2.1
        with:
          variableNames: MONGO_URI,AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET,AUTH0_REDIRECT_URI

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install --pure-lockfile

      - name: D1 Migrations Apply
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: 3.63.1
          command: d1 migrations apply donde-esta-tu-local --remote

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: 3.63.1
