name: Deploy

on:
  push:
    branches:
      - develop

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  AUTH0_CLIENT_ID: xxxx
  AUTH0_CLIENT_SECRET: xxxx
  AUTH0_REDIRECT_URI: http://localhost:5173/login/callback

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        uses: CallePuzzle/envvar-to-dotenv-action@v1.2.1
        with:
          variableNames: MONGO_URI,AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET,AUTH0_REDIRECT_URI

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install --pure-lockfile

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: 3.63.1
